# Generated by Django 3.2.8 on 2021-11-24 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_people_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='updated',
        ),
    ]
